# Register at https://openweathermap.org to get your API key
# If you don't want to write your key here, you can delete this line and use the OWM_API_KEY environment variable instead
api_key = "de59742fe3f0fe7939a6a05360132450"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "5388319"

# Output format, using Handlebars syntax, meaning variables should be used like {{ this }}
# Available tokens are:
# - temp_celcius
# - temp_kelvin
# - temp_fahrenheit
# - temp_icon
# - trend
# - forecast_celcius
# - forecast_kelvin
# - forecast_fahrenheit
# - forecast_icon
display = "{{ temp_icon }} {{ temp_fahrenheit }}°F"
# {{ trend }}" 
#{{ forecast_icon }} {{ forecast_celcius }}°C"
